[package]
name = "ai"
version = "0.5.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rand = "0.8.5"
image = "0.25.1"
nalgebra = "0.33.0"
libc = "0.2.155"
rand_distr = "0.4.3"
ndarray = "0.15.6"
approx = "0.5.1"
ndarray-rand = "0.14.0"
