name: Build and run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - run: cargo test --verbose
